<?php
// +----------------------------------------------------------------------
// | 用于请求接口的单元测试基类 [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2016-2017 limingxinleo All rights reserved.
// +----------------------------------------------------------------------
// | Author: limx <715557344@qq.com> <https://github.com/limingxinleo>
// +----------------------------------------------------------------------
namespace Tests;

use Phalcon\Mvc\Application;

abstract class HttpTestCase extends UnitTestCase
{
    public $application;

    protected function setUp()
    {
        parent::setUp();
        $this->application = new Application($this->di);
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @desc   JSON请求接口
     * @author limx
     * @param $method
     * @param $uri
     * @param $data
     */
    public function json($uri, $data = [])
    {
        $_SERVER['REQUEST_METHOD'] = "POST";
        $response = $this->application->handle($uri);
        return $response;
    }

    /**
     * @desc   Http接口模拟请求
     * @author limx
     * @param       $method 方法名
     * @param       $uri    路由
     * @param array $data   数据
     * @return mixed
     */
    public function request($method, $uri, $data = [])
    {
        $_SERVER['REQUEST_METHOD'] = $method;
        $_REQUEST = $data;
        $response = $this->application->handle($uri);
        return $response;
    }

    public function get($uri, $data = [])
    {
    }

    public function post($uri, $data = [])
    {
        return $this->request('POST', $uri, $data);
    }
}
